[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "Hack Nerd Font Mono"
bold.family = "Hack Nerd Font Mono"
italic.family = "Hack Nerd Font Mono"
bold_italic.family = "Hack Nerd Font Mono"

size = 6.0

[selection]
save_to_clipboard = true

